apps/api/urls.py
from django.urls import path, include
from rest_framework import routers

from apps.api.views import ApiKeyGeneratorView
from apps.debtors.api.views import DebtorViewSet
from apps.invoices.api.views import InvoiceViewSet


router = routers.SimpleRouter()

router.register('debtors', DebtorViewSet, 'debtors')
router.register('invoices', InvoiceViewSet, 'invoices')


urlpatterns = [
    path('api-key/', ApiKeyGeneratorView.as_view(), name='api-key'),
    path('v1/', include((router.urls, 'apps.api'), namespace='viewsets'))
]

apps/debtors/urls.py
from django.urls import path, include

from apps.debtors.views import DebtorView, CreateDebtorView, \
    DebtorDetailView, DeleteDebtorView

app_name = 'debtors'

urlpatterns = [
    path('', DebtorView.as_view(), name='debtors-list'),
    path('create/', CreateDebtorView.as_view(), name='debtors-create'),
    path('<int:debtor_id>/', DebtorDetailView.as_view(), name='debtors-detail'),
    path('<int:debtor_id>/delete/', DeleteDebtorView.as_view(),
         name='debtors-delete'),
    path('', include(('apps.invoices.urls', 'apps.invoices'),
                     namespace='invoices'))
]

apps/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from apps.users.views import LoginView, HomeView

app_name = 'users'

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('home/', HomeView.as_view(), name='home'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

moneybook/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.users.urls', 'users')),
    path('debtors/', include(('apps.debtors.urls', 'apps.debtors'),
                             namespace='debtors')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('api/', include(('apps.api.urls', 'apps.api'), namespace='api')),
]

templates/base/base-logged.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    {% block head %}
    {% endblock %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-dark navbar-expand-sm navbar-fixed-top navbar-custom">
    <a class="navbar-brand custom-brand" href="{% url 'users:home' %}"><b>MoneyBook</b></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'debtors:debtors-list' %}">Debtors</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'debtors:invoices:invoices-list' %}">Invoices</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'api:api-key' %}">Api</a>
            </li>
        </ul>
        <ul class="nav navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#"
                   id="navbarDropdownMenuLink" role="button"
                   data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">
                    {{ request.user.first_name }}
                </a>
                <div class="dropdown-menu"
                     aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'users:logout' %}">Log Out</a>
                </div>
            </li>
        </ul>
    </div>
</nav>
{% block content %}
{% endblock content %}
</body>
<style type="text/css">

    body {
        background-color: #417690;
    }

    a {
        color: inherit;
    }

    .navbar-dark.navbar-custom {
        background-color: #000000;
        color: #ffffff;
    }

    .navbar-brand.custom-brand {
        color: #f47902;
    }

    .navbar-brand.custom-brand:hover {
        color: #9f2e00;
    }
</style>
{% block style-script %}
{% endblock %}
</html>

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% block content %}
{% endblock content %}
</html>