apps/debtors/urls.py
from django.urls import path, include

from apps.debtors.views import DebtorView, CreateDebtorView, \
    DebtorDetailView, DeleteDebtorView

app_name = 'debtors'

urlpatterns = [
    path('', DebtorView.as_view(), name='debtors-list'),
    path('create/', CreateDebtorView.as_view(), name='debtors-create'),
    path('<int:debtor_id>/', DebtorDetailView.as_view(), name='debtors-detail'),
    path('<int:debtor_id>/delete/', DeleteDebtorView.as_view(),
         name='debtors-delete'),
    path('', include(('apps.invoices.urls', 'apps.invoices'),
                     namespace='invoices'))
]

moneybook/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.users.urls', 'users')),
    path('debtors/', include(('apps.debtors.urls', 'apps.debtors'),
                             namespace='debtors')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('api/', include(('apps.api.urls', 'apps.api'), namespace='api')),
]

apps/debtors/models.py
from django.db import models
from django.contrib.auth import get_user_model

from apps.invoices.models import InvoiceStatusChoices

user_model = get_user_model()


class Debtor(models.Model):
    """
    According to online information(google), maximum length
    of an IBAN is 34 characters
    """
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField()
    iban = models.CharField(max_length=34)
    responsible_admin = models.ForeignKey(user_model, db_index=True,
                                          on_delete=models.DO_NOTHING)

    @property
    def open_invoice_count(self):
        return self.invoice_set.filter(status=InvoiceStatusChoices.OPEN).count()

    @property
    def paid_invoice_count(self):
        return self.invoice_set.filter(status=InvoiceStatusChoices.PAID).count()

    @property
    def overdue_invoice_count(self):
        return self.invoice_set.filter(
            status=InvoiceStatusChoices.OVERDUE).count()

    @property
    def cancelled_invoice_count(self):
        return self.invoice_set.filter(
            status=InvoiceStatusChoices.CANCELLED).count()

    @property
    def full_name(self):
        return "{first_name} {last_name}".format(first_name=self.first_name,
                                                 last_name=self.last_name)

    class Meta:
        ordering = ['-pk']

apps/debtors/api/views.py
from rest_framework.viewsets import GenericViewSet
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin

from apps.debtors.api.filters import DebtorFilterSet
from apps.debtors.api.serializers import DebtorSerializer
from apps.debtors.models import Debtor


class DebtorViewSet(ListModelMixin, RetrieveModelMixin, GenericViewSet):
    queryset = Debtor.objects.all()
    serializer_class = DebtorSerializer
    http_method_names = ['get']
    filterset_class = DebtorFilterSet

apps/debtors/views.py
import logging

from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

from apps.debtors.models import Debtor
from apps.debtors.services import DebtorService

logger = logging.getLogger(__name__)


class DebtorView(LoginRequiredMixin, View):
    @staticmethod
    def render_debtor_page(request, send_notification=False,
                           is_operation_succeeded=False):
        debtors__qs = Debtor.objects.all()
        template_data = {
            'debtors': debtors__qs,
            'is_operation_succeeded': is_operation_succeeded,
            'send_notification': send_notification
        }
        return render(request, 'debtors/debtors_list.html', template_data)

    def get(self, request):
        return self.render_debtor_page(request=request)


class CreateDebtorView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'debtors/debtor_create.html')

    def post(self, request):
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        e_mail = request.POST.get('email')
        iban = request.POST.get('iban')

        debtor_service = DebtorService()
        try:
            debtor_service.create_debtor(
                first_name=first_name, last_name=last_name,
                e_mail=e_mail, iban=iban, respobsible_admin=request.user)

        except Exception as exc:
            logger.exception(exc)
            return DebtorView.render_debtor_page(
                request=request, send_notification=True,
                is_operation_succeeded=False)

        return DebtorView.render_debtor_page(
            request=request, send_notification=True,
            is_operation_succeeded=True)


class DebtorDetailView(LoginRequiredMixin, View):
    def get(self, request, debtor_id):
        try:
            debtor_instance = Debtor.objects.get(pk=debtor_id)
        except Debtor.DoesNotExist:
            return redirect('debtors:debtors-list')

        if debtor_instance.responsible_admin == request.user:
            return render(request, 'debtors/debtor_detail.html',
                          {'debtor': debtor_instance})

        return render(request, 'debtors/debtor_detail_disabled.html',
                      {'debtor': debtor_instance})

    def post(self, request, debtor_id):
        try:
            debtor_instance = Debtor.objects.get(pk=debtor_id,
                                                 responsible_admin=request.user)
        except Debtor.DoesNotExist:
            return redirect('debtors-list')

        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        iban = request.POST.get('iban')

        try:
            debtor_service = DebtorService()
            debtor_service.update_debtor(
                instance=debtor_instance, first_name=first_name,
                last_name=last_name, email=email, iban=iban)
        except Exception as exc:
            logger.exception(exc)
            return DebtorView.render_debtor_page(
                request=request, send_notification=True,
                is_operation_succeeded=False)

        return DebtorView.render_debtor_page(
            request=request, send_notification=True,
            is_operation_succeeded=True)


class DeleteDebtorView(View):
    def post(self, request, debtor_id):
        try:
            debtor_instance = Debtor.objects.get(pk=debtor_id,
                                                 responsible_admin=request.user)
        except Debtor.DoesNotExist:
            return redirect('debtors-list')

        try:
            debtor_service = DebtorService()
            debtor_service.delete_debtor(instance=debtor_instance)
        except Exception as exc:
            logger.exception(exc)
            return DebtorView.render_debtor_page(
                request=request, send_notification=True,
                is_operation_succeeded=False)

        return DebtorView.render_debtor_page(
            request=request, send_notification=True,
            is_operation_succeeded=True)

apps/debtors/templates/debtors/debtor_create.html
{% extends 'base/base-logged.html' %}
{% block content %}
    <div class="row justify-content-center" id="form-row">
        <div class="col-md-6">
            <div class="jumbotron">
                <h4 class="display-5">Add Debtor</h4>
                <hr class="my-4">
                <form method="post">{% csrf_token %}
                    <div class="form-group">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstName">First Name</label>
                                <input type="text" class="form-control"
                                       name="first_name" id="firstName"
                                       placeholder="First Name"
                                       required="required">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastName">Last Name</label>
                                <input type="text" class="form-control"
                                       name="last_name" id="lastName"
                                       placeholder="Last Name"
                                       required="required">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email">E-Mail</label>
                        <input type="email" class="form-control" name="email"
                               placeholder="E-Mail" id="email" required="required">
                    </div>
                    <div class="form-group">
                        <label for="iban">Iban</label>
                        <input type="text" class="form-control" name="iban"
                               placeholder="Iban" id="iban" required="required">
                    </div>
                    <a href="{% url 'debtors:debtors-list' %}" class="btn btn-secondary">
                        back
                    </a>
                    <div class="float-right">
                        <button type="submit" class="btn btn-success">
                            Save Debtor
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}
{% block style-script %}
    <style type="text/css">
        #form-row {
            margin-top: 5em;
        }
    </style>
{% endblock %}

apps/debtors/templates/debtors/debtor_detail.html
{% extends 'base/base-logged.html' %}
{% block content %}
    <div class="row justify-content-center" id="form-row">
        <div class="col-md-6">
            <div class="jumbotron">
                <h6 class="display-5">Responsible
                    Admin: {{ debtor.responsible_admin.username }}</h6>
                <hr class="my-4">
                <form method="post">{% csrf_token %}
                    <div class="form-group">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstName">First Name</label>
                                <input type="text" class="form-control"
                                       name="first_name"
                                       value="{{ debtor.first_name }}"
                                       placeholder="First Name"
                                       required="required" id="firstName">

                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastName">Last Name</label>
                                <input type="text" class="form-control"
                                       name="last_name"
                                       value="{{ debtor.last_name }}"
                                       placeholder="Last Name"
                                       required="required" id="lastName">

                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email">E-Mail</label>
                        <input type="email" class="form-control" name="email"
                               value="{{ debtor.email }}" id="email"
                               placeholder="E-Mail" required="required">
                    </div>
                    <div class="form-group">
                        <label for="iban">Iban</label>
                        <input type="text" class="form-control" name="iban"
                               value="{{ debtor.iban }}" id="iban"
                               placeholder="Iban" required="required">
                    </div>
                    <a href="{% url 'debtors:debtors-list' %}"
                       class="btn btn-secondary">back
                    </a>
                    <a class="btn btn-warning" href="{% url 'debtors:invoices:invoice-debtor-list' debtor_id=debtor.pk %}">
                        Invoices
                    </a>

                    <button type="button" data-toggle="modal"
                            data-target="#cancelModal"
                            class="btn btn-danger">
                        Delete Debtor
                    </button>
                    <div class="float-right">
                        <button type="submit" class="btn btn-success">Update
                            Debtor
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Cancel Modal -->
    <div class="modal fade" id="cancelModal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                            aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure about deleting debtor? All invoices belonging to this debtor will be deleted.</p>
                </div>
                <div class="modal-footer">
                    <div class="float-left">
                        <button type="button" class="btn btn-secondary"
                                data-dismiss="modal">No
                        </button>
                    </div>
                    <div class="float-right">
                        <form action="{% url 'debtors:debtors-delete' debtor_id=debtor.pk %}"
                              method="post">{% csrf_token %}
                            <input type="hidden" name="cancel"
                                   value="something"/>
                            <button type="submit" class="btn btn-danger">
                                Delete
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block style-script %}
    <style type="text/css">
        #form-row {
            margin-top: 5em;
        }
    </style>
{% endblock %}

apps/debtors/templates/debtors/debtor_detail_disabled.html
{% extends 'base/base-logged.html' %}
{% block content %}
    <div class="row justify-content-center" id="form-row">
        <div class="col-md-6">
            <div class="jumbotron">
                <h6 class="display-5">Responsible
                    Admin: {{ debtor.responsible_admin.username }}</h6>
                <hr class="my-4">
                    <div class="form-group">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstName">First Name</label>
                                <input type="text" class="form-control"
                                       name="first_name" id="firstName"
                                       value="{{ debtor.first_name }}" readonly>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="lastName">Last Name</label>
                                <input type="text" class="form-control"
                                       name="last_name" id="lastName"
                                       value="{{ debtor.last_name }}"
                                       placeholder="Last Name"
                                       required="required" readonly>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email">E-Mail</label>
                        <input type="email" class="form-control" name="email"
                               value="{{ debtor.email }}" id="email" readonly>
                    </div>
                    <div class="form-group">
                        <label for="iban">Iban</label>
                        <input type="text" class="form-control" name="iban"
                               value="{{ debtor.iban }}" id="iban" readonly>
                    </div>
                    <a href="{% url 'debtors:debtors-list' %}"
                       class="btn btn-secondary">back
                    </a>
                    <a class="btn btn-warning" href="{% url 'debtors:invoices:invoice-debtor-list' debtor_id=debtor.pk %}">
                        Invoices
                    </a>
            </div>
        </div>
    </div>
{% endblock %}
{% block style-script %}
    <style type="text/css">
        #form-row {
            margin-top: 5em;
        }
    </style>
{% endblock %}

apps/debtors/templates/debtors/debtors_list.html
{% extends 'base/base-logged.html' %}
{% block head %}
    <link rel="stylesheet" type="text/css"
          href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script type="text/javascript" charset="utf8"
            src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
{% endblock %}
{% block content %}
    <div class="row justify-content-center" id="table-row">
        <div class="col-md-8">
            <div class="jumbotron">
                <h3>Debtors</h3>
                <hr class="my-4">
                <table id="table1" class="display"></table>
                <hr class="my-4">
                <div class="row justify-content-center">
                    <a href="{% url 'debtors:debtors-create' %}"
                       class="btn btn-success">
                        Add
                        Debtor
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Notification Modal -->
    <div class="modal fade" id="notification-modal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <p id="notification-modal-message">Operation succeeded!</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary"
                            data-dismiss="modal">Close
                    </button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block style-script %}
    <style type="text/css">
        #table-row {
            margin-top: 5em;
        }

        /* resizes table */
        .dataTables_wrapper {
            font-size: 13px;
        }
    </style>

    <script>
        var dataSet = [
            {% if not debtors %}
                ["-", "-", "-", "-", "-", "-", "-", "-",],
            {% else %}
                {% for debtor in debtors %}
                    [
                        "{{ debtor.first_name }}",
                        "{{ debtor.last_name }}",
                        "{{ debtor.email }}",
                        "{{ debtor.open_invoice_count }}",
                        "{{ debtor.paid_invoice_count }}",
                        "{{ debtor.overdue_invoice_count }}",
                        "{{ debtor.cancelled_invoice_count }}",
                        {% if debtor.responsible_admin == request.user %}
                            "<a class=\"btn btn-info btn-sm\" href=\"{% url 'debtors:debtors-detail' debtor_id=debtor.pk %}\">details</a>",
                        {% else %}
                            "<a class=\"btn btn-secondary btn-sm\" href=\"{% url 'debtors:debtors-detail' debtor_id=debtor.pk %}\">details</a>",
                        {% endif %}
                    ],
                {% endfor %}
            {% endif %}
        ];
        $(document).ready(function () {
            $('#table1').DataTable({
                data: dataSet,
                columns: [
                    {title: "First Name"},
                    {title: "Last Name"},
                    {title: "E-Mail"},
                    {title: "Open Invoice Count"},
                    {title: "Paid Invoice Count"},
                    {title: "Overdue Invoice Count"},
                    {title: "Cancelled Invoice Count"},
                    {title: "Details"}
                ]
            });
        });
        $('#modal-success').modal('show');
        $(document).ready(function () {
            {% if send_notification %}
                {% if is_operation_succeeded %}
                    $("#notification-modal").modal('show');
                {% else %}
                    $("#notification-modal-message")[0].innerText = "Operation failed!";
                    $("#notification-modal").modal('show');
                {% endif %}
            {% endif %}
        });
    </script>
{% endblock %}